// Command pinupdate keeps the installer's runtime pins current. It finds the
// latest upstream Proton-CachyOS (SLR) and umu-launcher releases, downloads
// them, checks their SHA-256 against GitHub's published digest, checks every
// candidate Proton against workflow.ProtonContract, and verifies the current
// Astarte Launcher's Authenticode signature. Pins that pass are written to
// pkg/config/versions.go and the generated table in docs/runtime-pins.md.
//
// It runs from .github/workflows/update-pins.yml, which opens a pull request
// with the result. Locally:
//
//	go run ./tools/pinupdate -summary /tmp/pins.md
//	go run ./tools/pinupdate -proton-tag cachyos-11.0-20260703-slr -force
package main

import (
	"archive/tar"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/xi2/xz"

	"bellum-installer/pkg/config"
	"bellum-installer/pkg/packages"
	"bellum-installer/pkg/workflow"
)

const (
	protonRepo   = "CachyOS/proton-cachyos"
	umuRepo      = "Open-Wine-Components/umu-launcher"
	versionsFile = "pkg/config/versions.go"
	pinsDocFile  = "docs/runtime-pins.md"
	docBegin     = "<!-- pins:begin (generated by tools/pinupdate; do not edit) -->"
	docEnd       = "<!-- pins:end -->"
)

var client = &http.Client{Timeout: time.Hour}

type release struct {
	TagName    string  `json:"tag_name"`
	Draft      bool    `json:"draft"`
	Prerelease bool    `json:"prerelease"`
	HTMLURL    string  `json:"html_url"`
	Assets     []asset `json:"assets"`
}

type asset struct {
	Name   string `json:"name"`
	URL    string `json:"browser_download_url"`
	Digest string `json:"digest"` // "sha256:<hex>" on releases GitHub has digested
}

// pins is the subset of config.Versions this tool manages.
type pins struct {
	ProtonVer, ProtonSHA256, WinetricksVer string
	UMUVersion, UMUZipappSHA256            string
	LauncherSHA256Allowlist                []string
}

type report struct {
	changes, notes, failures []string
}

func (r *report) change(format string, a ...any) {
	r.changes = append(r.changes, fmt.Sprintf(format, a...))
}
func (r *report) note(format string, a ...any) { r.notes = append(r.notes, fmt.Sprintf(format, a...)) }
func (r *report) failure(format string, a ...any) {
	r.failures = append(r.failures, fmt.Sprintf(format, a...))
}

func main() {
	summary := flag.String("summary", "", "write a Markdown summary to this file")
	protonTag := flag.String("proton-tag", "", "use this Proton-CachyOS tag instead of the latest release")
	umuTag := flag.String("umu-tag", "", "use this umu-launcher tag instead of the latest release")
	force := flag.Bool("force", false, "re-verify pins even when the versions are unchanged")
	skipLauncher := flag.Bool("skip-launcher", false, "don't download and verify the Astarte Launcher")
	flag.Parse()

	cur := pins{
		ProtonVer:               config.DefaultVersions.ProtonVer,
		ProtonSHA256:            config.DefaultVersions.ProtonSHA256,
		WinetricksVer:           config.DefaultVersions.WinetricksVer,
		UMUVersion:              config.DefaultVersions.UMUVersion,
		UMUZipappSHA256:         config.DefaultVersions.UMUZipappSHA256,
		LauncherSHA256Allowlist: append([]string{}, config.DefaultVersions.LauncherSHA256Allowlist...),
	}
	next := cur
	var r report

	if err := updateProton(&next, *protonTag, *force, &r); err != nil {
		r.failure("Proton: %v", err)
	}
	if err := updateUMU(&next, *umuTag, *force, &r); err != nil {
		r.failure("umu-launcher: %v", err)
	}
	if !*skipLauncher {
		if err := updateLauncher(&next, &r); err != nil {
			r.failure("Astarte Launcher: %v", err)
		}
	}

	changed := false
	if next.ProtonVer != cur.ProtonVer || next.ProtonSHA256 != cur.ProtonSHA256 || next.WinetricksVer != cur.WinetricksVer ||
		next.UMUVersion != cur.UMUVersion || next.UMUZipappSHA256 != cur.UMUZipappSHA256 ||
		len(next.LauncherSHA256Allowlist) != len(cur.LauncherSHA256Allowlist) {
		changed = true
		if err := writeVersions(versionsFile, next); err != nil {
			r.failure("update %s: %v", versionsFile, err)
		}
	}
	if err := writePinsDoc(pinsDocFile, next); err != nil {
		r.failure("update %s: %v", pinsDocFile, err)
	}

	md := renderSummary(r, changed)
	fmt.Print(md)
	if *summary != "" {
		if err := os.WriteFile(*summary, []byte(md), 0644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
	if out := os.Getenv("GITHUB_OUTPUT"); out != "" {
		f, err := os.OpenFile(out, os.O_APPEND|os.O_WRONLY, 0)
		if err == nil {
			fmt.Fprintf(f, "changed=%t\nfailed=%t\n", changed, len(r.failures) > 0)
			f.Close()
		}
	}
	if len(r.failures) > 0 {
		os.Exit(2)
	}
}

// --- Proton -------------------------------------------------------------------

var protonTagRe = regexp.MustCompile(`^cachyos-[0-9.]+-[0-9]{8}-slr$`)

func protonAssetName(tag string) string { return "proton-" + tag + "-x86_64.tar.xz" }

// pickProton returns the newest stable SLR release that has the x86_64 archive.
func pickProton(releases []release, tag string) (release, asset, error) {
	for _, rel := range releases {
		if rel.Draft || rel.Prerelease || !protonTagRe.MatchString(rel.TagName) || (tag != "" && rel.TagName != tag) {
			continue
		}
		for _, a := range rel.Assets {
			if a.Name == protonAssetName(rel.TagName) {
				return rel, a, nil
			}
		}
	}
	return release{}, asset{}, errors.New("no stable SLR x86_64 release found")
}

func updateProton(p *pins, tag string, force bool, r *report) error {
	var rel release
	var a asset
	if tag != "" {
		// An explicit tag skips the API (useful where api.github.com is blocked).
		rel = release{TagName: tag, HTMLURL: "https://github.com/" + protonRepo + "/releases/tag/" + tag}
		a = asset{Name: protonAssetName(tag), URL: fmt.Sprintf("https://github.com/%s/releases/download/%s/%s", protonRepo, tag, protonAssetName(tag))}
	} else {
		releases, err := listReleases(protonRepo)
		if err != nil {
			return err
		}
		if rel, a, err = pickProton(releases, ""); err != nil {
			return err
		}
	}
	ver := strings.TrimSuffix(a.Name, ".tar.xz")
	if ver == p.ProtonVer && !force {
		r.note("Proton `%s` is still the latest SLR release.", ver)
		return nil
	}

	wanted := map[string]bool{}
	for _, req := range workflow.ProtonContract() {
		wanted[req.Path] = true
	}
	work, err := os.MkdirTemp("", "pinupdate-proton-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(work)
	archivePath := filepath.Join(work, a.Name)
	archive, err := os.Create(archivePath)
	if err != nil {
		return err
	}
	sum, files, err := downloadProton(a.URL, wanted, archive)
	if closeErr := archive.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return err
	}
	if err := checkDigest(a, sum); err != nil {
		return err
	}
	var missing []string
	for _, req := range workflow.ProtonContract() {
		if !strings.Contains(string(files[req.Path]), req.Needle) {
			missing = append(missing, fmt.Sprintf("`%s` lacks `%s` (%s)", req.Path, req.Needle, req.Why))
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("[%s](%s) breaks the installer's Proton contract:\n  - %s", ver, rel.HTMLURL, strings.Join(missing, "\n  - "))
	}
	// Unpack it exactly as the installer does, so an archive our extractor
	// rejects (as happened with protonfixes' relative symlinks) never gets
	// pinned.
	if err := packages.ExtractPackageTo(archivePath, filepath.Join(work, "tree"), 1); err != nil {
		return fmt.Errorf("[%s](%s) does not unpack with the installer's extractor: %v", ver, rel.HTMLURL, err)
	}
	wt := winetricksVersion(files["protonfixes/winetricks"])
	if ver == p.ProtonVer && sum != p.ProtonSHA256 {
		return fmt.Errorf("the published archive for %s no longer matches the pinned SHA-256 (%s, now %s); investigate before re-pinning", ver, p.ProtonSHA256, sum)
	}
	if ver != p.ProtonVer {
		r.change("Proton `%s` → [`%s`](%s) (SHA-256 `%s`); all %d contract checks pass and it unpacks with the installer's extractor.", p.ProtonVer, ver, rel.HTMLURL, sum, len(workflow.ProtonContract()))
	} else {
		r.note("Proton `%s` re-verified: digest, all %d contract checks and a full unpack pass.", ver, len(workflow.ProtonContract()))
	}
	p.ProtonVer, p.ProtonSHA256 = ver, sum
	if wt != "" {
		newWT := "bundled with pinned Proton (" + wt + ")"
		if newWT != p.WinetricksVer {
			r.change("winetricks (bundled with Proton) → `%s`.", wt)
			p.WinetricksVer = newWT
		}
	}
	return nil
}

// downloadProton streams the archive once, hashing it and keeping the files
// named in wanted (paths relative to the archive's top directory).
func downloadProton(url string, wanted map[string]bool, keep io.Writer) (string, map[string][]byte, error) {
	resp, err := client.Get(url)
	if err != nil {
		return "", nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", nil, fmt.Errorf("download %s: %s", url, resp.Status)
	}
	h := sha256.New()
	sink := io.MultiWriter(h, keep)
	xzr, err := xz.NewReader(io.TeeReader(resp.Body, sink), 0)
	if err != nil {
		return "", nil, err
	}
	files := map[string][]byte{}
	tr := tar.NewReader(xzr)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return "", nil, err
		}
		_, rel, ok := strings.Cut(hdr.Name, "/")
		if ok && wanted[rel] && hdr.Typeflag == tar.TypeReg {
			if files[rel], err = io.ReadAll(tr); err != nil {
				return "", nil, err
			}
		}
	}
	// Hash any trailing bytes the tar reader didn't consume.
	if _, err := io.Copy(io.Discard, io.TeeReader(resp.Body, sink)); err != nil {
		return "", nil, err
	}
	return hex.EncodeToString(h.Sum(nil)), files, nil
}

var winetricksVersionRe = regexp.MustCompile(`(?m)^WINETRICKS_VERSION=([^\s]+)`)

func winetricksVersion(script []byte) string {
	if m := winetricksVersionRe.FindSubmatch(script); m != nil {
		return string(m[1])
	}
	return ""
}

// --- umu-launcher -------------------------------------------------------------

func umuAssetName(tag string) string { return "umu-launcher-" + tag + "-zipapp.tar" }

func pickUMU(releases []release, tag string) (release, asset, error) {
	for _, rel := range releases {
		if rel.Draft || rel.Prerelease || (tag != "" && rel.TagName != tag) {
			continue
		}
		for _, a := range rel.Assets {
			if a.Name == umuAssetName(rel.TagName) {
				return rel, a, nil
			}
		}
	}
	return release{}, asset{}, errors.New("no stable release with a zipapp found")
}

func updateUMU(p *pins, tag string, force bool, r *report) error {
	var rel release
	var a asset
	if tag != "" {
		rel = release{TagName: tag, HTMLURL: "https://github.com/" + umuRepo + "/releases/tag/" + tag}
		a = asset{Name: umuAssetName(tag), URL: fmt.Sprintf("https://github.com/%s/releases/download/%s/%s", umuRepo, tag, umuAssetName(tag))}
	} else {
		releases, err := listReleases(umuRepo)
		if err != nil {
			return err
		}
		if rel, a, err = pickUMU(releases, ""); err != nil {
			return err
		}
	}
	if rel.TagName == p.UMUVersion && !force {
		r.note("umu-launcher `%s` is still the latest release.", rel.TagName)
		return nil
	}
	data, err := fetch(a.URL)
	if err != nil {
		return err
	}
	sum := sha256.Sum256(data)
	hexSum := hex.EncodeToString(sum[:])
	if err := checkDigest(a, hexSum); err != nil {
		return err
	}
	if !tarHasFile(data, "umu/umu-run") {
		return fmt.Errorf("%s has no umu/umu-run", a.Name)
	}
	if rel.TagName == p.UMUVersion {
		if hexSum != p.UMUZipappSHA256 {
			return fmt.Errorf("the published %s no longer matches the pinned SHA-256; investigate before re-pinning", a.Name)
		}
		r.note("umu-launcher `%s` re-verified.", rel.TagName)
		return nil
	}
	r.change("umu-launcher `%s` → [`%s`](%s) (SHA-256 `%s`).", p.UMUVersion, rel.TagName, rel.HTMLURL, hexSum)
	p.UMUVersion, p.UMUZipappSHA256 = rel.TagName, hexSum
	return nil
}

func tarHasFile(data []byte, name string) bool {
	tr := tar.NewReader(strings.NewReader(string(data)))
	for {
		hdr, err := tr.Next()
		if err != nil {
			return false
		}
		if hdr.Name == name && hdr.Typeflag == tar.TypeReg {
			return true
		}
	}
}

// --- Astarte Launcher ---------------------------------------------------------

func updateLauncher(p *pins, r *report) error {
	data, err := fetch(packages.LauncherInstallerURL)
	if err != nil {
		return err
	}
	dir, err := os.MkdirTemp("", "pinupdate-launcher-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(dir)
	path := filepath.Join(dir, "AstarteLauncher-amd64-installer.exe")
	if err := os.WriteFile(path, data, 0600); err != nil {
		return err
	}
	if err := packages.VerifyLauncherAuthenticode(path); err != nil {
		return err
	}
	sum := sha256.Sum256(data)
	digest := hex.EncodeToString(sum[:])
	for _, known := range p.LauncherSHA256Allowlist {
		if strings.EqualFold(known, digest) {
			r.note("Astarte Launcher build `%s` is already in the allowlist.", digest[:12])
			return nil
		}
	}
	r.change("Astarte Launcher: new build `%s`, signed by `%s`, added to the allowlist.", digest, config.DefaultVersions.LauncherSigner)
	p.LauncherSHA256Allowlist = append(p.LauncherSHA256Allowlist, digest)
	return nil
}

// --- GitHub and downloads -----------------------------------------------------

func listReleases(repo string) ([]release, error) {
	req, err := http.NewRequest(http.MethodGet, "https://api.github.com/repos/"+repo+"/releases?per_page=30", nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	if token := os.Getenv("GITHUB_TOKEN"); token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("list %s releases: %s", repo, resp.Status)
	}
	var releases []release
	return releases, json.NewDecoder(resp.Body).Decode(&releases)
}

func fetch(url string) ([]byte, error) {
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download %s: %s", url, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

// checkDigest compares against GitHub's published asset digest when present.
func checkDigest(a asset, sum string) error {
	if want, ok := strings.CutPrefix(a.Digest, "sha256:"); ok && !strings.EqualFold(want, sum) {
		return fmt.Errorf("%s: downloaded SHA-256 %s differs from GitHub's published digest %s", a.Name, sum, want)
	}
	return nil
}

// --- Writing pins ---------------------------------------------------------------

func setField(src, field, value string) (string, error) {
	re := regexp.MustCompile(`(?m)^(\s*` + field + `:\s*)"[^"]*"`)
	if !re.MatchString(src) {
		return "", fmt.Errorf("field %s not found", field)
	}
	return re.ReplaceAllString(src, `${1}"`+value+`"`), nil
}

func setAllowlist(src, field string, values []string) (string, error) {
	re := regexp.MustCompile(`(?m)^(\s*` + field + `:\s*)\[\]string\{[^}]*\}`)
	if !re.MatchString(src) {
		return "", fmt.Errorf("field %s not found", field)
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = `"` + v + `"`
	}
	return re.ReplaceAllString(src, `${1}[]string{`+strings.Join(quoted, ", ")+`}`), nil
}

func writeVersions(path string, p pins) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	src := string(b)
	for _, kv := range [][2]string{
		{"ProtonVer", p.ProtonVer}, {"ProtonSHA256", p.ProtonSHA256}, {"WinetricksVer", p.WinetricksVer},
		{"UMUVersion", p.UMUVersion}, {"UMUZipappSHA256", p.UMUZipappSHA256},
	} {
		if src, err = setField(src, kv[0], kv[1]); err != nil {
			return err
		}
	}
	if src, err = setAllowlist(src, "LauncherSHA256Allowlist", p.LauncherSHA256Allowlist); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(src), 0644)
}

func pinsTable(p pins) string {
	protonTag := strings.TrimSuffix(strings.TrimPrefix(p.ProtonVer, "proton-"), "-x86_64")
	var b strings.Builder
	b.WriteString(docBegin + "\n")
	b.WriteString("| Component | Pinned version | SHA-256 |\n| --- | --- | --- |\n")
	fmt.Fprintf(&b, "| CachyOS Proton SLR | [`%s`](https://github.com/%s/releases/tag/%s) | `%s` |\n", p.ProtonVer, protonRepo, protonTag, p.ProtonSHA256)
	fmt.Fprintf(&b, "| winetricks | %s | covered by the Proton archive |\n", p.WinetricksVer)
	fmt.Fprintf(&b, "| umu-launcher (zipapp) | [`%s`](https://github.com/%s/releases/tag/%s) | `%s` |\n", p.UMUVersion, umuRepo, p.UMUVersion, p.UMUZipappSHA256)
	fmt.Fprintf(&b, "| Astarte Launcher (known builds; signature is the hard control) | current | %s |\n", "`"+strings.Join(p.LauncherSHA256Allowlist, "`, `")+"`")
	b.WriteString(docEnd)
	return b.String()
}

func writePinsDoc(path string, p pins) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	src := string(b)
	i, j := strings.Index(src, docBegin), strings.Index(src, docEnd)
	if i < 0 || j < i {
		return fmt.Errorf("generated pins block markers not found")
	}
	src = src[:i] + pinsTable(p) + src[j+len(docEnd):]
	return os.WriteFile(path, []byte(src), 0644)
}

func renderSummary(r report, changed bool) string {
	var b strings.Builder
	b.WriteString("## Runtime pin update\n\n")
	switch {
	case len(r.failures) > 0:
		b.WriteString("**Some checks failed.** The failing components were left at their current pins.\n\n")
	case changed:
		b.WriteString("New upstream releases passed every check.\n\n")
	default:
		b.WriteString("Everything is up to date.\n\n")
	}
	section := func(title string, items []string) {
		if len(items) == 0 {
			return
		}
		b.WriteString("### " + title + "\n\n")
		for _, it := range items {
			b.WriteString("- " + it + "\n")
		}
		b.WriteString("\n")
	}
	section("Failures", r.failures)
	section("Changes", r.changes)
	section("Checked", r.notes)
	return b.String()
}
