package workflow

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"bellum-installer/pkg/core"
)

// ConfigureConfig holds configuration for post-install configuration
type ConfigureConfig struct {
	WINEPREFIX      string
	ProtonPath      string
	GPUType         string
	GPUCapabilities core.GPUCapabilities
	IsAMDGPU        bool
	Workdir         string
	IsFSR41         bool
}

// RunConfiguration runs the post-install configuration phase
func RunConfiguration(config ConfigureConfig, logger *core.Logger) error {
	return RunConfigurationWithBoundaries(config, logger, DefaultBoundaries)
}

// RunConfigurationWithBoundaries runs configuration using injectable host effects.
func RunConfigurationWithBoundaries(config ConfigureConfig, logger *core.Logger, boundaries WorkflowBoundaries) error {
	if boundaries.Commands == nil {
		boundaries.Commands = DefaultBoundaries.Commands
	}
	if boundaries.Files == nil {
		boundaries.Files = DefaultBoundaries.Files
	}
	boundaries.Files = GuardGameTreeWrites{
		FileStore:      boundaries.Files,
		GameInstallDir: filepath.Join(config.WINEPREFIX, "drive_c", "Program Files", "Astarte Industries", "Bellum"),
	}
	if boundaries.MutatePrefix == nil {
		boundaries.MutatePrefix = boundaries.Commands.Run
	}
	fmt.Println()
	logger.Info("Starting configuration phase...")

	// Update DLL overrides
	task := core.StartTask("Setting DLL overrides")
	logFile := ""
	if config.Workdir != "" {
		logFile = filepath.Join(config.Workdir, "logs", "installer.log")
	}
	err := updateDLLsWith(boundaries.MutatePrefix, logger, logFile)
	task.Done(err)
	if err != nil {
		return err
	}

	// GPU-specific configuration: the single most-stable-then-fastest set
	// for the detected launch profile.
	extras := launchVarsToggles()
	caps := config.GPUCapabilities
	switch profile := core.LaunchProfileFor(caps); {
	case caps.NVAPI:
		// dxvk_nvapi is included in Proton for NVIDIA
		if err := createLaunchVarsFileNvidia(config.WINEPREFIX, config.ProtonPath, extras, logger, boundaries.Files); err != nil {
			return err
		}
	case caps.Vendor == core.GPUAMD:
		fsr4 := config.IsFSR41 && profile.UsesFSR4Upgrade()
		if err := createLaunchVarsFileAMD(config.WINEPREFIX, config.ProtonPath, amdLaunchSettings{FSR4Upgrade: fsr4, RDNA3Workaround: profile.UsesRDNA3Workaround()}, extras, logger, boundaries.Files); err != nil {
			return err
		}
	default:
		if err := createLaunchVarsFileGeneric(config.WINEPREFIX, config.ProtonPath, extras, boundaries.Files); err != nil {
			return err
		}
	}

	logger.Info("[OK] Configuration phase complete!")
	fmt.Println()

	return nil
}

// UpdateDLLs sets up DLL overrides for the WINEPREFIX
func UpdateDLLs(logger *core.Logger) error {
	return updateDLLsWith(DefaultBoundaries.MutatePrefix, logger, "")
}

func updateDLLsWith(mutate func(core.RunMode, []string, *core.Logger, string) error, logger *core.Logger, logFile string) error {
	// System-wide overrides
	systemDLLs := []string{
		"d3d12",
		"d3d12core",
		"d3d10core",
		"d3d9",
		"d3d8",
	}

	for _, dll := range systemDLLs {
		if err := mutate(core.RunModeSilent, umuRun("reg", "add", `HKEY_CURRENT_USER\Software\Wine\DllOverrides`, "/v", dll, "/d", "native,builtin", "/f"), logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s", dll))
			return err
		}
	}

	// Application-specific overrides for d3d11 and dxgi
	appDLLs := []string{"d3d11", "dxgi"}

	for _, dll := range appDLLs {
		// Launcher overrides
		if err := mutate(core.RunModeSilent, umuRun("reg", "add", `HKCU\Software\Wine\AppDefaults\AstarteLauncher.exe\DllOverrides`, "/v", dll, "/d", "builtin", "/f"), logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s (launcher)", dll))
			return err
		}

		// Game overrides
		if err := mutate(core.RunModeSilent, umuRun("reg", "add", `HKCU\Software\Wine\AppDefaults\Bellum-Win64-Shipping.exe\DllOverrides`, "/v", dll, "/d", "native", "/f"), logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s (game)", dll))
			return err
		}
	}

	return nil
}

// CreateLaunchVarsFileNvidia creates the launch environment file for NVIDIA GPUs
func CreateLaunchVarsFileNvidia(wineprefix, protonpath string, logger *core.Logger) error {
	return createLaunchVarsFileNvidia(wineprefix, protonpath, launchVarsToggles(), logger, DefaultBoundaries.Files)
}

// In the pinned Proton, NVAPI is on by default (only PROTON_DISABLE_NVAPI
// turns it off) and nvngx.dll is copied from the NVIDIA driver whenever it is
// present, so DLSS needs no flag here. PROTON_NVIDIA_LIBS adds the CUDA,
// NVENC, NVML and OptiX bridges.
func createLaunchVarsFileNvidia(wineprefix, protonpath, extras string, logger *core.Logger, files FileStore) error {
	launchVars := filepath.Join(wineprefix, "launch_vars.env")
	logger.Info(fmt.Sprintf("Creating launch environment file: %s", launchVars))

	content := `# Bellum Launch Variables (NVIDIA)
# Auto-generated by Bellum Linux Installer

export PROTONPATH=` + quoteShellEnv(protonpath) + `
export BELLUM_UMU_RUN=` + quoteShellEnv(umuRunBinary) + `
export PROTON_EAC_RUNTIME=` + quoteShellEnv(eacRuntimePath()) + `
export WINEPREFIX=` + quoteShellEnv(wineprefix) + `
export STEAM_COMPAT_DATA_PATH=` + quoteShellEnv(wineprefix) + `
export STEAM_COMPAT_SHADER_PATH="shadercache"
export STEAM_COMPAT_CLIENT_INSTALL_PATH=""
export PROTON_DXVK_D3D8="1"
export PROTON_NVIDIA_LIBS="1"
export PROTON_DLSS_UPGRADE="0"
export MALLOC_ARENA_MAX="1"
export VKD3D_CONFIG="descriptor_heap"
export WINEESYNC="1"
export WINEFSYNC="1"
export DXVK_NVAPI="1"
export DXVK_ENABLE_NVAPI="1"
export WINE_LARGE_ADDRESS_AWARE="1"
export CUDA_DISABLE_PERF_BOOST="1"
` + extras

	if err := files.WriteFile(launchVars, []byte(content), 0600); err != nil {
		logger.Error(fmt.Sprintf("Failed to create launch vars file: %v", err))
		return err
	}

	logger.Info("[OK] Launch environment file created")
	return nil
}

// amdLaunchSettings are the two AMD settings that differ by generation.
type amdLaunchSettings struct {
	FSR4Upgrade     bool
	RDNA3Workaround bool
}

// CreateLaunchVarsFileAMD creates the launch environment file for AMD GPUs.
// isFSR41 selects the RDNA4 settings; otherwise the RDNA3 settings are
// written, as before profiles existed.
func CreateLaunchVarsFileAMD(wineprefix, protonpath string, isFSR41 bool, logger *core.Logger) error {
	return createLaunchVarsFileAMD(wineprefix, protonpath, amdLaunchSettings{FSR4Upgrade: isFSR41, RDNA3Workaround: !isFSR41}, launchVarsToggles(), logger, DefaultBoundaries.Files)
}

func createLaunchVarsFileAMD(wineprefix, protonpath string, settings amdLaunchSettings, extras string, logger *core.Logger, files FileStore) error {
	launchVars := filepath.Join(wineprefix, "launch_vars.env")
	logger.Info(fmt.Sprintf("Creating launch environment file: %s", launchVars))

	// The pinned Proton downloads AMD's FSR4 driver component (amdxcffx64)
	// at every launch, and its amdxc64 shim offers FSR4 to FidelityFX-API
	// games when the GPU reports support. PROTON_FSR4_UPGRADE=1 forces that
	// offer; we set it only on an unambiguous RDNA4 (native FP8 path).
	// DXIL_SPIRV_CONFIG=wmma_rdna3_workaround makes amdxc64 take the FP16
	// emulation path ("not recommended" in its own log). It targets RDNA3's
	// matrix instructions, so only the RDNA3 profile keeps it (the existing,
	// known behaviour; CachyOS notes it is rarely needed there now). RDNA2
	// (the Steam Deck included), older and unknown AMD generations get
	// neither: the game falls back to its own FSR 3.x.
	fsr4Upgrade := "0"
	if settings.FSR4Upgrade {
		fsr4Upgrade = "1"
	}
	dxilWorkaround := ""
	if settings.RDNA3Workaround && !settings.FSR4Upgrade {
		dxilWorkaround = "export DXIL_SPIRV_CONFIG=wmma_rdna3_workaround\n"
	}

	content := `# Bellum Launch Variables (AMD)
# Auto-generated by Bellum Linux Installer

export PROTONPATH=` + quoteShellEnv(protonpath) + `
export BELLUM_UMU_RUN=` + quoteShellEnv(umuRunBinary) + `
export PROTON_EAC_RUNTIME=` + quoteShellEnv(eacRuntimePath()) + `
export WINEPREFIX=` + quoteShellEnv(wineprefix) + `
export PROTON_FSR4_UPGRADE="` + fsr4Upgrade + `"
export STEAM_COMPAT_DATA_PATH=` + quoteShellEnv(wineprefix) + `
export PROTON_DXVK_D3D8="1"
export PROTON_DLSS_UPGRADE="0"
export MALLOC_ARENA_MAX="1"
export VKD3D_CONFIG="descriptor_heap"
export WINE_LARGE_ADDRESS_AWARE="1"
` + dxilWorkaround + extras

	if err := files.WriteFile(launchVars, []byte(content), 0600); err != nil {
		logger.Error(fmt.Sprintf("Failed to create launch vars file: %v", err))
		return err
	}

	logger.Info("[OK] Launch environment file created")
	return nil
}

func quoteShellEnv(value string) string { return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'" }

func createLaunchVarsFileGeneric(wineprefix, protonpath, extras string, files FileStore) error {
	content := "# Bellum launch variables\n" +
		"export PROTONPATH=" + quoteShellEnv(protonpath) + "\n" +
		"export BELLUM_UMU_RUN=" + quoteShellEnv(umuRunBinary) + "\n" +
		"export PROTON_EAC_RUNTIME=" + quoteShellEnv(eacRuntimePath()) + "\n" +
		"export WINEPREFIX=" + quoteShellEnv(wineprefix) + "\n" +
		"export STEAM_COMPAT_DATA_PATH=" + quoteShellEnv(wineprefix) + "\n" +
		"export PROTON_FSR4_UPGRADE=0\nexport PROTON_DLSS_UPGRADE=0\nexport PROTON_DXVK_D3D8=1\n" +
		"export MALLOC_ARENA_MAX=1\nexport VKD3D_CONFIG=descriptor_heap\nexport WINE_LARGE_ADDRESS_AWARE=1\n" +
		extras
	return files.WriteFile(filepath.Join(wineprefix, "launch_vars.env"), []byte(content), 0600)
}

// copyFile copies a file from src to dst
func copyFile(src, dst string) error {
	source, err := os.Open(src)
	if err != nil {
		return err
	}
	defer source.Close()

	destination, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer destination.Close()

	_, err = destination.ReadFrom(source)
	return err
}
