package workflow

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	cfg "bellum-installer/pkg/config"
	"bellum-installer/pkg/core"
)

// ConfigureConfig holds configuration for post-install configuration
type ConfigureConfig struct {
	WINEPREFIX      string
	ProtonPath      string
	GPUType         string
	GPUCapabilities core.GPUCapabilities
	IsAMDGPU        bool
	Workdir         string
	IsFSR4          bool
}

// RunConfiguration runs the post-install configuration phase
func RunConfiguration(config ConfigureConfig, logger *core.Logger) error {
	return RunConfigurationWithBoundaries(config, logger, DefaultBoundaries)
}

// RunConfigurationWithBoundaries runs configuration using injectable host effects.
func RunConfigurationWithBoundaries(config ConfigureConfig, logger *core.Logger, boundaries WorkflowBoundaries) error {
	if boundaries.Commands == nil {
		boundaries.Commands = DefaultBoundaries.Commands
	}
	if boundaries.Files == nil {
		boundaries.Files = DefaultBoundaries.Files
	}
	boundaries.Files = GuardGameTreeWrites{
		FileStore:      boundaries.Files,
		GameInstallDir: filepath.Join(config.WINEPREFIX, "drive_c", "Program Files", "Astarte Industries", "Bellum"),
	}
	if boundaries.MutatePrefix == nil {
		boundaries.MutatePrefix = boundaries.Commands.Run
	}
	fmt.Println()
	logger.Info("Starting configuration phase...")

	// Update DLL overrides
	if err := updateDLLsWith(boundaries.MutatePrefix, logger); err != nil {
		return err
	}

	// GPU-specific configuration
	if config.GPUCapabilities.NVAPI {
		if err := createLaunchVarsFileNvidia(config.WINEPREFIX, config.ProtonPath, logger, boundaries.Files); err != nil {
			return err
		}
		// dxvk_nvapi is included in Proton for NVIDIA
	} else if config.GPUCapabilities.Vendor == core.GPUAMD {
		if err := createLaunchVarsFileAMD(config.WINEPREFIX, config.ProtonPath, config.IsFSR4 && config.GPUCapabilities.FSR4, logger, boundaries.Files); err != nil {
			return err
		}
	} else {
		if err := createLaunchVarsFileGeneric(config.WINEPREFIX, config.ProtonPath, boundaries.Files); err != nil {
			return err
		}
	}

	logger.Info("[OK] Configuration phase complete!")
	fmt.Println()

	return nil
}

// UpdateDLLs sets up DLL overrides for the WINEPREFIX
func UpdateDLLs(logger *core.Logger) error {
	return updateDLLsWith(DefaultBoundaries.MutatePrefix, logger)
}

func updateDLLsWith(mutate func(core.RunMode, []string, *core.Logger, string) error, logger *core.Logger) error {
	logger.Info("Setting DLL overrides")

	wine := cfg.DefaultVersions.Binaries.Wine
	logFile := ""

	// System-wide overrides
	systemDLLs := []string{
		"d3d12",
		"d3d12core",
		"d3d10core",
		"d3d9",
		"d3d8",
	}

	for _, dll := range systemDLLs {
		if err := mutate(core.RunModeSilent, []string{wine, "reg", "add", `HKEY_CURRENT_USER\Software\Wine\DllOverrides`, "/v", dll, "/d", "native,builtin", "/f"}, logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s", dll))
			return err
		}
	}

	// Application-specific overrides for d3d11 and dxgi
	appDLLs := []string{"d3d11", "dxgi"}

	for _, dll := range appDLLs {
		// Launcher overrides
		if err := mutate(core.RunModeSilent, []string{wine, "reg", "add", `HKCU\Software\Wine\AppDefaults\AstarteLauncher.exe\DllOverrides`, "/v", dll, "/d", "builtin", "/f"}, logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s (launcher)", dll))
			return err
		}

		// Game overrides
		if err := mutate(core.RunModeSilent, []string{wine, "reg", "add", `HKCU\Software\Wine\AppDefaults\Bellum-Win64-Shipping.exe\DllOverrides`, "/v", dll, "/d", "native", "/f"}, logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s (game)", dll))
			return err
		}
	}

	return nil
}

// CreateLaunchVarsFileNvidia creates the launch environment file for NVIDIA GPUs
func CreateLaunchVarsFileNvidia(wineprefix, protonpath string, logger *core.Logger) error {
	return createLaunchVarsFileNvidia(wineprefix, protonpath, logger, DefaultBoundaries.Files)
}

func createLaunchVarsFileNvidia(wineprefix, protonpath string, logger *core.Logger, files FileStore) error {
	launchVars := filepath.Join(wineprefix, "launch_vars.env")
	logger.Info(fmt.Sprintf("Creating launch environment file: %s", launchVars))

	content := `# Bellum Launch Variables (NVIDIA)
# Auto-generated by Bellum Linux Installer

export PROTONPATH=` + quoteShellEnv(protonpath) + `
export PROTON_EAC_RUNTIME=` + quoteShellEnv(eacRuntimePath()) + `
export WINEPREFIX=` + quoteShellEnv(wineprefix) + `
export STEAM_COMPAT_DATA_PATH=` + quoteShellEnv(wineprefix) + `
export STEAM_COMPAT_SHADER_PATH="shadercache"
export STEAM_COMPAT_CLIENT_INSTALL_PATH=""
export PROTON_ENABLE_NGX_UPDATER="0"
export PROTON_ENABLE_NVAPI="1"
export PROTON_VKD3D_HEAP="1"
export PROTON_DXVK_D3D8="1"
export PROTON_NVIDIA_LIBS="1"
export PROTON_DLSS_UPGRADE="0"
export MALLOC_ARENA_MAX="1"
export VKD3D_CONFIG="descriptor_heap"
export WINEESYNC="1"
export WINEFSYNC="1"
export DXVK_NVAPI="1"
export DXVK_ENABLE_NVAPI="1"
export DXVK_NVAPIHACK="0"
export WINE_LARGE_ADDRESS_AWARE="1"
export CUDA_DISABLE_PERF_BOOST="1"
`

	if err := files.WriteFile(launchVars, []byte(content), 0600); err != nil {
		logger.Error(fmt.Sprintf("Failed to create launch vars file: %v", err))
		return err
	}

	logger.Info("[OK] Launch environment file created")
	return nil
}

// CreateLaunchVarsFileAMD creates the launch environment file for AMD GPUs
func CreateLaunchVarsFileAMD(wineprefix, protonpath string, isFSR4 bool, logger *core.Logger) error {
	return createLaunchVarsFileAMD(wineprefix, protonpath, isFSR4, logger, DefaultBoundaries.Files)
}

func createLaunchVarsFileAMD(wineprefix, protonpath string, isFSR4 bool, logger *core.Logger, files FileStore) error {
	launchVars := filepath.Join(wineprefix, "launch_vars.env")
	logger.Info(fmt.Sprintf("Creating launch environment file: %s", launchVars))

	// The pinned runtime auto-stages amdxcffx64.dll on supported RDNA2-RDNA4
	// GPUs. Supply its FSR4 request/version preference only for RDNA4; absence
	// on RDNA3 does not disable the runtime's automatic DLL staging.
	fsr4Upgrade := ""
	if isFSR4 {
		fsr4Upgrade = "1"
	}
	fsr4Environment := ""
	if fsr4Upgrade != "" {
		fsr4Environment = `export PROTON_FSR4_UPGRADE="` + fsr4Upgrade + `"` + "\n"
	}

	content := `# Bellum Launch Variables (AMD)
# Auto-generated by Bellum Linux Installer

export PROTONPATH=` + quoteShellEnv(protonpath) + `
export PROTON_EAC_RUNTIME=` + quoteShellEnv(eacRuntimePath()) + `
export WINEPREFIX=` + quoteShellEnv(wineprefix) + `
` + fsr4Environment + `
export STEAM_COMPAT_DATA_PATH=` + quoteShellEnv(wineprefix) + `
export PROTON_VKD3D_HEAP="1"
export VKD3D_CONFIG="descriptor_heap"
export WINE_LARGE_ADDRESS_AWARE="1"
`

	if err := files.WriteFile(launchVars, []byte(content), 0600); err != nil {
		logger.Error(fmt.Sprintf("Failed to create launch vars file: %v", err))
		return err
	}

	logger.Info("[OK] Launch environment file created")
	return nil
}

func eacRuntimePath() string {
	if path := os.Getenv("PROTON_EAC_RUNTIME"); path != "" {
		return path
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "Steam", "steamapps", "common", "Proton EasyAntiCheat Runtime")
}

func quoteShellEnv(value string) string { return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'" }

func createLaunchVarsFileGeneric(wineprefix, protonpath string, files FileStore) error {
	content := "# Bellum launch variables\n" +
		"export PROTONPATH=" + quoteShellEnv(protonpath) + "\n" +
		"export PROTON_EAC_RUNTIME=" + quoteShellEnv(eacRuntimePath()) + "\n" +
		"export WINEPREFIX=" + quoteShellEnv(wineprefix) + "\n" +
		"export STEAM_COMPAT_DATA_PATH=" + quoteShellEnv(wineprefix) + "\n" +
		"export PROTON_DLSS_UPGRADE=0\n"
	return files.WriteFile(filepath.Join(wineprefix, "launch_vars.env"), []byte(content), 0600)
}

// copyFile copies a file from src to dst
func copyFile(src, dst string) error {
	source, err := os.Open(src)
	if err != nil {
		return err
	}
	defer source.Close()

	destination, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer destination.Close()

	_, err = destination.ReadFrom(source)
	return err
}
